# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7s25ftgb196-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Moon/Desktop/PLD_filter/PLD_filter1.cache/wt [current_project]
set_property parent.project_path C:/Users/Moon/Desktop/PLD_filter/PLD_filter1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  c:/Users/Moon/Desktop/IP_Core/Frequency-Divider-IP
  c:/Users/Moon/Desktop/IP_Core/RGB2DVI_IP
} [current_project]
set_property ip_output_repo c:/Users/Moon/Desktop/PLD_filter/PLD_filter1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/dot.coe
add_files C:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/t0.coe
add_files C:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/t1.coe
add_files C:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/t2.coe
add_files C:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/t3.coe
add_files C:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/t4.coe
add_files C:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/t5.coe
add_files C:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/t6.coe
add_files C:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/t7.coe
add_files C:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/t8.coe
add_files C:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/t9.coe
add_files C:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/title.coe
add_files C:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/freq.coe
add_files C:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/max.coe
read_verilog -library xil_defaultlib {
  C:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/sources_1/new/DACtest_128.v
  C:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/sources_1/new/Driver_ADC.v
  C:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/sources_1/new/Driver_HDMI.v
  C:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/sources_1/new/FIR_128.v
  C:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/sources_1/new/Freq_Cal.v
  C:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/sources_1/new/HDMI_top.v
  C:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/sources_1/new/MCP4725_init.v
  C:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/sources_1/new/clk_div.v
  C:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/sources_1/new/i2c_drive.v
  C:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/sources_1/new/i2c_top.v
  C:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/sources_1/new/num_display.v
  C:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/sources_1/new/osd_display.v
  C:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/sources_1/new/timing_gen_xy.v
  C:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/sources_1/new/uart_blue.v
  C:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/sources_1/new/uart_rx.v
  C:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/sources_1/new/uart_rx_blue.v
  C:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/sources_1/new/uart_top.v
  C:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/sources_1/new/video_generator.v
  C:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/sources_1/new/top_128.v
}
read_ip -quiet C:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/sources_1/ip/rgb2dvi_0/rgb2dvi_0.xci
set_property used_in_implementation false [get_files -all c:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/sources_1/ip/rgb2dvi_0/src/rgb2dvi.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/sources_1/ip/rgb2dvi_0/src/rgb2dvi_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/sources_1/ip/rgb2dvi_0/src/rgb2dvi_clocks.xdc]

read_ip -quiet C:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/sources_1/ip/Wave_Ram/Wave_Ram.xci
set_property used_in_implementation false [get_files -all c:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/sources_1/ip/Wave_Ram/Wave_Ram_ooc.xdc]

read_ip -quiet C:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/sources_1/ip/Clk_Division_0/Clk_Division_0.xci

read_ip -quiet C:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all c:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet C:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/sources_1/ip/mem_dot/mem_dot.xci
set_property used_in_implementation false [get_files -all c:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/sources_1/ip/mem_dot/mem_dot_ooc.xdc]

read_ip -quiet C:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/sources_1/ip/mem_0/mem_0.xci
set_property used_in_implementation false [get_files -all c:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/sources_1/ip/mem_0/mem_0_ooc.xdc]

read_ip -quiet C:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/sources_1/ip/mem_1/mem_1.xci
set_property used_in_implementation false [get_files -all c:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/sources_1/ip/mem_1/mem_1_ooc.xdc]

read_ip -quiet C:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/sources_1/ip/mem_2/mem_2.xci
set_property used_in_implementation false [get_files -all c:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/sources_1/ip/mem_2/mem_2_ooc.xdc]

read_ip -quiet C:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/sources_1/ip/mem_3/mem_3.xci
set_property used_in_implementation false [get_files -all c:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/sources_1/ip/mem_3/mem_3_ooc.xdc]

read_ip -quiet C:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/sources_1/ip/mem_4/mem_4.xci
set_property used_in_implementation false [get_files -all c:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/sources_1/ip/mem_4/mem_4_ooc.xdc]

read_ip -quiet C:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/sources_1/ip/mem_5/mem_5.xci
set_property used_in_implementation false [get_files -all c:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/sources_1/ip/mem_5/mem_5_ooc.xdc]

read_ip -quiet C:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/sources_1/ip/mem_6/mem_6.xci
set_property used_in_implementation false [get_files -all c:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/sources_1/ip/mem_6/mem_6_ooc.xdc]

read_ip -quiet C:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/sources_1/ip/mem_7/mem_7.xci
set_property used_in_implementation false [get_files -all c:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/sources_1/ip/mem_7/mem_7_ooc.xdc]

read_ip -quiet C:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/sources_1/ip/mem_8/mem_8.xci
set_property used_in_implementation false [get_files -all c:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/sources_1/ip/mem_8/mem_8_ooc.xdc]

read_ip -quiet C:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/sources_1/ip/mem_9/mem_9.xci
set_property used_in_implementation false [get_files -all c:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/sources_1/ip/mem_9/mem_9_ooc.xdc]

read_ip -quiet C:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/sources_1/ip/osd_rom/osd_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/sources_1/ip/osd_rom/osd_rom_ooc.xdc]

read_ip -quiet C:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/sources_1/ip/osd_rom_freq/osd_rom_freq.xci
set_property used_in_implementation false [get_files -all c:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/sources_1/ip/osd_rom_freq/osd_rom_freq_ooc.xdc]

read_ip -quiet C:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/sources_1/ip/osd_rom_max/osd_rom_max.xci
set_property used_in_implementation false [get_files -all c:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/sources_1/ip/osd_rom_max/osd_rom_max_ooc.xdc]

read_ip -quiet C:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1.xci
set_property used_in_implementation false [get_files -all c:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/constrs_1/new/system.xdc
set_property used_in_implementation false [get_files C:/Users/Moon/Desktop/PLD_filter/PLD_filter1.srcs/constrs_1/new/system.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top top_128 -part xc7s25ftgb196-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_128.dcp
create_report "synth_2_synth_report_utilization_0" "report_utilization -file top_128_utilization_synth.rpt -pb top_128_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
