# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/24238/Desktop/PLD/PLD_filter1/PLD_filter/PLD_filter.srcs/sources_1/ip/osd_rom/osd_rom.xci
# IP: The module: 'osd_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/24238/Desktop/PLD/PLD_filter1/PLD_filter/PLD_filter.srcs/sources_1/ip/osd_rom/osd_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'osd_rom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/24238/Desktop/PLD/PLD_filter1/PLD_filter/PLD_filter.srcs/sources_1/ip/osd_rom/osd_rom.xci
# IP: The module: 'osd_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/24238/Desktop/PLD/PLD_filter1/PLD_filter/PLD_filter.srcs/sources_1/ip/osd_rom/osd_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'osd_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
