# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/system.xdc

# IP: ip/Wave_Ram/Wave_Ram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Wave_Ram || ORIG_REF_NAME==Wave_Ram} -quiet] -quiet

# IP: ip/rgb2dvi_0/rgb2dvi_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rgb2dvi_0 || ORIG_REF_NAME==rgb2dvi_0} -quiet] -quiet

# XDC: ip/Wave_Ram/Wave_Ram_ooc.xdc

# XDC: ip/rgb2dvi_0/src/rgb2dvi.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==rgb2dvi_0 || ORIG_REF_NAME==rgb2dvi_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/rgb2dvi_0/src/rgb2dvi_ooc.xdc

# XDC: ip/rgb2dvi_0/src/rgb2dvi_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==rgb2dvi_0 || ORIG_REF_NAME==rgb2dvi_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
